name: Build Vips-IS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Global variables available to all jobs
env:
  REGISTRY: ghcr.io
  # IMAGE_NAME evaluates to 'username/repository'
  IMAGE_NAME: ${{ github.repository }}
  BASE_IMAGE: ghcr.io/${{ github.repository }}/vips-is-base:latest

jobs:
  build-base:
    runs-on: ubuntu-latest
    outputs:
      base_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if base image changed
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: docker/vis-is-base.Dockerfile

      - name: Log in to GHCR
        if: steps.changed-files.outputs.any_changed == 'true'|| github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Base Image
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/vips-is-base:latest \
            -f docker/vis-is-base.Dockerfile .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/vips-is-base:latest

  build-app:
    needs: build-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Build, Tests and Coverage
        run: |
          mvn test jacoco:report --batch-mode

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Quarkus Unit Tests
          path: '**/target/surefire-reports/*.xml'
          reporter: java-junit

      - name: Jacoco Report to Summary
        uses: madrapps/jacoco-report@v1.7.1
        if: always()
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          title: "Code Coverage Report"
          comment-type: summary

      - name: Package Application
        run: mvn package -DskipTests --batch-mode

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push App Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/vips-is-app.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
