name: Build Vips-IS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest
    outputs:
      base_changed: ${{ steps.changed-files.outputs.any_changed }}
      image_name: ${{ steps.prep.outputs.repo }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare naming and check changes
        id: prep
        run: |
          echo "repo=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
          echo "image=ghcr.io/${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      - name: Check if base image changed
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: docker/vis-is-base.Dockerfile

      - name: Log in to GHCR
        if: steps.changed-files.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Base Image
        if: steps.changed-files.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          docker build \
            -t ${{ env.image }}/vips-is-base:latest \
            -f docker/vips-is-base.Dockerfile .
          docker push ${{ env.image }}/vips-is-base:latest

  build-app:
    needs: build-base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Set Image Name
        run: echo "image=ghcr.io/${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Build and Tests
        run: mvn test jacoco:report --batch-mode

      - name: Package Application
        run: mvn package -DskipTests --batch-mode

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push App Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/vips-is-app.Dockerfile
          push: true
          build-args: |
            BASE_IMAGE=${{ env.image }}/vips-is-base:latest
          tags: ${{ env.image }}:latest
